spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/darolmar/resurrection-clould-config
# Defines the port where the config server is running so that rest of the services can pick up 
# their external configurations
server:
  port: 8888    